language: objective-c
xcode_project: MSCircularSliderExample/MSCircularSliderExample.xcodeproj
xcode_scheme: MSCircularSliderExample
script: xctool -project MSCircularSliderExample/MSCircularSliderExample.xcodeproj -scheme MSCircularSliderExample build  CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
