language: swift
osx_image: xcode9.0

xcode_project: MSCircularSliderExample/MSCircularSliderExample.xcodeproj

branches:
only:
- master

install: true

after_success:
- bash <(curl -s https://codecov.io/bash)